-- MySQL Script generated by MySQL Workbench
-- Thu May  6 21:00:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`usuario` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `password` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`administrador` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`),
  INDEX `idusuarioA_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `idusuarioA`
    FOREIGN KEY (`idusuario`)
    REFERENCES `proyecto`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`paquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`paquete` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`paquete` (
  `idpaquete` INT NOT NULL,
  `origen` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`idpaquete`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`repartidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`repartidor` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`repartidor` (
  `idrepartidor` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrepartidor`),
  INDEX `idusuarior_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `idusuarior`
    FOREIGN KEY (`idusuario`)
    REFERENCES `proyecto`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`moto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`moto` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`moto` (
  `idmoto` INT NOT NULL,
  `idrepartido` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idpaquete` INT NOT NULL,
  PRIMARY KEY (`idmoto`),
  INDEX `idrepartidorR_idx` (`idrepartido` ASC) VISIBLE,
  INDEX `idpaquete_idx` (`idpaquete` ASC) VISIBLE,
  CONSTRAINT `idpaquete`
    FOREIGN KEY (`idpaquete`)
    REFERENCES `proyecto`.`paquete` (`idpaquete`),
  CONSTRAINT `idrepartidorR`
    FOREIGN KEY (`idrepartido`)
    REFERENCES `proyecto`.`repartidor` (`idrepartidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`pie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`pie` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`pie` (
  `idrepartidor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idpaquete` INT NOT NULL,
  PRIMARY KEY (`idrepartidor`),
  INDEX `idpaqueteA_idx` (`idpaquete` ASC) VISIBLE,
  CONSTRAINT `idpaqueteA`
    FOREIGN KEY (`idpaquete`)
    REFERENCES `proyecto`.`paquete` (`idpaquete`),
  CONSTRAINT `idrepartidor`
    FOREIGN KEY (`idrepartidor`)
    REFERENCES `proyecto`.`repartidor` (`idrepartidor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
